const ctrl = require(`../server/controller`)
const Sequelize = require(`sequelize`);

const { CONNECTION_STRING } = process.env;

const sequelize = new Sequelize(CONNECTION_STRING, {
  dialect: `postgres`,
  dialectOptions: {
    ssl: {
      rejectUnauthorized: false,
    },
  },
});

const popArtists = [
  "Ariana Grande",
  `ed sheeran`,
  `Lady Gaga`,
  `Mariah Carey`,
  `Tyler, The Creator`,
  `Cardi B`,
  `Charlie Puth`,
  `Beyonce`,
  `Miley Cyrus`,
  `Bruno Mars`,
  `Billie Eilish`,
  `Dua Lipa`,
  `Shawn Mendes`,
  `Camila Cabello`,
  `Harry Styles`,
  `Taylor Swift`,
  `Selena Gomez`,
  `Rihanna`,
  `Halsey`,
];

const rapArtists = [
  `Pooh Shiesty`,
  `Travis Scott`,
  `lil uzi vert`,
  `jakc harlow`,
  `youngboy never broke again`,
  `kid laroi`,
  `dababy`,
  `giveon`,
  `kanye west`,
  `j. cole`,
  `megan thee stallion`,
  `moneybagg yo`,
  `rod wave`,
  `polo g`,
  `juice wrld`,
  `lil durk`,
  `the weeknd`,
  `doja cat`,
  `lil baby`,
  `pop smoke`,
  `drake`,
];

const edmArtists = [
  `David Guetta`,
  `swedish house mafia`,
  `martin garrix`,
  `sonny fedora`,
  `kygo`,
  `don diablo`,
  `lost frequencies`,
  `skrillex`,
  `alan walker`,
  `meduza`,
  `imanbek`,
  `disclosure`,
  `morten`,
  `illenium`,
  `calvin harris`,
]

const rockArtists = [
  `altin gun`,
  `architects`,
  `bachelor`,
  `backspace`,
  `black country, new road`,
  `black midi`,
  `blk jks`,
  `the brothers osborne`,
  `chai`,
  `coheed and cambria`,
  `combo chimbita`,
  `dead heat`,
  `dogleg`,
  `drive-by truckers`,
  `dry cleaning`,
  `fiddlehead`,
  `the flaming lips`,
  `crumb`
]

const rnbArtists = [
  `Brent faiyaz`,
  `Daniel Caesar`,
  `Frank Ocean`,
  `Pink Seat$`,
  `Steve Lacy`,
  `HER`,
  `UMI`,
  `Jaden`,
  `Ella Mai`,
  `Silk Sonic`,
  `Luaryn Hill`,
  `Snoh Aalegra`,
  `Anderson .PAAk`,
  `6lack`,
  `Giveon`,
  `Smino`,
  `Sabrina Claudio`,
  `Clairo`,
  `Bryson Tiller`,
  `Lana Del Ray`,
  `kaash Paige`,
  `Post Malone`,
  `Summer Walker`,
  `Majid Jordan`,
  `Rihanna`,
  `Sonder`,
  `ODIE`,
  `Bruno Mars`,
  `Elah Hale`,
  `Isaiah Rashad`,
  `Mac Ayres`,
  `Don Toliver`,
  `Khalid`,
  `SZA`,
  `Umi`,
  `chance the rapper`,
  `the weeknd`,
  `benee`,
  `Jazmine Sullivan`,
]

const latinArtists = [
  `Bad Bunny`,
  `Rauw Alejandro`,
  `Karol G`,
  `Kali Uchis`,
  `J Balvin`,
  `Jhay Cortez`,
  `Ozuna`,
  `Maluma`,
  `Myke Towers`,
  `Eslabon Armando`,
]

const kpopArtists = [
  `BTS`,
  `BLACKPINK`,
  `TWICE`,
  `STRAY KIDS`,
  `TOMORROW X TOGETHER`,
  `IU`,
  `SEVENTEEN`,
  `ITZY`,
  `EXO`,
  `RED VELVET`,
  `ENGYPEN`,
  `NCT DREAM`,
  `NCT 127`,
  `(G)I-DLE`,
  `ATEEZ`,
  `MAMAMOO`,
  `ROSE`,
]

const countryArtists = [
  `thomas rhett`,
  `morgan wallen`,
  `luke combs`,
  `kane brown`,
  `jason aldean`,
  `chris stapleton`,
  `luke bryan`,
  `carrie underwood`,
  `florida geargia line`,
  `blake shelton`,
  `tyler childers`,
  `kenny chesney`,
  `miranda lambert`,
  `tim mcgraw`
]

const metalArtists = [
  `Iron Maiden`,
  `mastodon`,
  `lorn`,
  `converge`,
  `architects`,
  `limp bizkit`,
  `avenged sevenfold`,
  `spiritbox`,
  `disturbed`,
  `slipknot`,
  `meshuggah`,
  `slay3er`,
  `cannibal corpse`,
  `evanscence`,
  `the black daglia murder`,
  `dream theater`,
  `between the bureid and me`
]
